name: Nebari Deploy

on:
  workflow_dispatch:
    # TODO: Remove duplication of inputs from here and nebari/action.yml
    inputs:
      nebari-version:
        description: 'Nebari Version'
        required: false
        default: "2022.10.1"
      project-name:
        description: 'Nebari Project Name'
        required: false
        default: "nebarideploy"
      vendor:
        description: 'Cloud Provider'
        required: false
        default: "aws"
      github-repository:
        description: 'GitHub Repository for Nebari Deployment'
        required: true
        default: "aktech/aktech-nebari"
      ciprovider:
        description: 'CI/CD Provider'
        required: false
        default: "github-actions"
      domain:
        description: 'Nebari Domain'
        required: true
        default: "nebari.iamit.in"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Nebari
    steps:
      - uses: actions/checkout@v3
      - name: secrets-to-env-action
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - id: nebari
        uses: ./.github/actions/nebari
        with:
          nebari-version: ${{ inputs.nebari-version }}
          project-name: ${{ inputs.project-name }}
          vendor: ${{ inputs.vendor }}
          github-repository: ${{ inputs.github-repository }}
          ciprovider: ${{ inputs.ciprovider }}
          domain: ${{ inputs.domain }}
